### PR TITLE
Use vim.bindeval() to avoid Unicode problems

### LINKED ISSUE #690: Error expanding snippet with encoding=utf-8 on windows
Vim version:  7.4.1023, Windows GUI

Expanding a snippet causes the following error, but **only** when `encoding=utf-8`.  It doesn't seem to matter what `fileencoding` is set to, only `encoding`.

To be clear, I don't think this is a problem with the snippet, since it works with `encoding=latin1` for example.  Additionally, the snippet still expands when `encoding=utf-8`, I just get the error message too.

This doesn't happen on the same machine when using Cygwin, vim version 7.4.663.

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "U:\vimfiles\plugged\ultisnips\pythonx\UltiSnips\snippet_manager.py", line 61, in wrapper
    return func(self, *args, **kwds)
  File "U:\vimfiles\plugged\ultisnips\pythonx\UltiSnips\snippet_manager.py", line 166, in expand
    if not self._try_expand():
  File "U:\vimfiles\plugged\ultisnips\pythonx\UltiSnips\snippet_manager.py", line 763, in _try_expand
    self._do_snippet(snippet, before)
  File "U:\vimfiles\plugged\ultisnips\pythonx\UltiSnips\snippet_manager.py", line 734, in _do_snippet
    self._jump()
  File "U:\vimfiles\plugged\ultisnips\pythonx\UltiSnips\snippet_manager.py", line 525, in _jump
    _vim.select(ntab.start, ntab.end)
  File "U:\vimfiles\plugged\ultisnips\pythonx\UltiSnips\_vim.py", line 162, in select
    _unmap_select_mode_mapping()
  File "U:\vimfiles\plugged\ultisnips\pythonx\UltiSnips\_vim.py", line 241, in _unmap_select_mode_mapping
    all_maps = list(filter(len, eval(r"_tmp_smaps").splitlines()))
  File "U:\vimfiles\plugged\ultisnips\pythonx\UltiSnips\_vim.py", line 117, in eval
    rv = vim.eval(as_vimencoding(text))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 1343: invalid start byte
```

### PR DESCRIPTION
**Pull request by mgedmin**
Fixes #690.

### CODE REVIEW

**Comment by Shougo** [comment]
`vim.bindeval()` is not supported in neovim and older Vim.
You should check it.

**Comment by mgedmin** [comment]
The Travis test failures are caused by a test that should be skipped on vim >= 7.4.214 but isn't skipped because Vim 8.0.0005 doesn't have patch 214.

**Comment by mgedmin** [comment]
I can rebase on master once #754 is merged.

**Comment by seletskiy** [comment]
@mgedmin: Merged.

**Comment by mgedmin** [comment]
Rebased.

**Comment by mgedmin** [comment]
Can I do anything else to help get this merged?

**Comment by seletskiy** [comment]
@mgedmin: Sorry for looong waiting time. Merged. Thank you!

**Pull request merged**
