### PR TITLE
Allow creating snippet on BufNewFile

### PR DESCRIPTION
**Pull request by srydell**
Hi!

First of all I want to thank you for this great plugin! It has helped me a lot.

I'm using a small plugin [srydell/vim-skeleton](https://github.com/srydell/vim-skeleton) to create templates using UltiSnips upon entering a new file. When I last updated ultisnips, the behaviour at BufNewFile had changed, and I could no longer jump through tabstops in the template snippets. A git bisect later and I found [this commit](https://github.com/SirVer/ultisnips/commit/8ff301c651d6df806c0f9305273a6c62a693bc48) to be where the behaviour changed. This PR is the smallest change I could manage that I think solves both cases.

Thanks for your time!

### CODE REVIEW

**Comment by SirVer** [comment]
Two comments:

1) That change was made deliberately in #1055 though, I assume. @thomasfaingnaert, you made #1055 and change that line from `Leave` to `Enter`. Do you still remember why that was useful or needed? I feel that two needs are clashing here, and toggling this back and forth does not seem a very prinicipled approach to finding a solution for both use cases.

2) Is it possible to add a test for this behavior? In light of the argumentation for 1), not having tests makes it likely that this will regress in the future.

**Comment by thomasfaingnaert** [comment]
It's been a while, but IIRC, it's because `BufEnter` is run _after_ Vim switches to another buffer, whereas `BufLeave` is run _before_. Because I need to check if the current or previous buffer is the preview window, I need to use `BufEnter`, since at `BufLeave` the buffer isn't changed yet. Thus, if Vim switches from a regular buffer to the preview window, it isn't detected on `BufLeave`.

I'm not sure yet how you could fix both issues, though.

**Comment by srydell** [comment]
I see. We would need tests for both use cases. @thomasfaingnaert, is the way described in #822 (found it when I followed #1055) the best way to reproduce the error related to the preview window?

I can add a test for vim-skeleton. I will try to add a test for the preview, but it will probably take more time.

**Comment by thomasfaingnaert** [comment]
@srydell Personally, I stumbled on the issue when using `completeopt+=preview` with vim-lsp and the python language server. When I started completion while a snippet was active, the snippet context was torn down, because apparently Vim switched to the preview window and back. It could even be that this workaround is not even needed anymore in the latest Vim, I'm not sure. #822 does seem to be the same issue, so you can use that to repro as well.

Since floating popups have been added to Vim, I haven't found much use anymore for the preview window, but it would still be nice to support it for people that do.

**Comment by srydell** [comment]
Thanks @thomasfaingnaert. I will poke around a bit when I get the time. I don't want to break anything, so I'll try to test as much as I'll have time to.

**Comment by SirVer** [comment]
@srydell Any update on this?

**Comment by srydell** [comment]
@SirVer I haven't had the time yet. Sorry.

**Comment by SirVer** [comment]
@srydell Closing this, let me know if you start working on it again. More than happy to reopen then.

**Pull request closed without merging**
