### PR TITLE
add function isExpandable(): check if expands, but do not expand

### PR DESCRIPTION
**Pull request by Konfekt**
A first take at https://github.com/SirVer/ultisnips/issues/786:

Add a function UltiSnips#isExpandable() (as neosnippet offers in guise of neosnippet#expandable()), useful for example for autocompletion plug-ins like delimitmate:
```vim
 nnoremap <expr> <tab> delimitMate#isEmptyPair() && UltiSnips#isExpandable() ? <del>:UltiSnips#Expand() : '<tab>'
```
This way, a snippet with delimiters such as
```vim
  snippet [
	[${1:text}](http://${2:address})
```
in markdown.snippets of vim-snippets, is expanded with no trailing ] (auto-inserted by the autocompletion plugin).

### CODE REVIEW

**Comment by seletskiy** [comment]
@Konfekt: great work! Can you add test with `isExpandable()` call?

**Comment by Konfekt** [comment]
There is now a test. However, I am not sure it does what's expected. Could you look over it?

**Comment by seletskiy** [comment]
@Konfekt: test is failing on travis. Does it work on your local setup. BTW, sorry for long waiting time.

**Comment by Konfekt** [comment]
My test is wrong. I imagined:
```
======================================================================

FAIL: runTest (test_isExpandable.SimpleExpand_ExpectCorrectResult)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/SirVer/ultisnips/test/vim_test_case.py", line 58, in runTest

    self.assertMultiLineEqual(self.output, wanted)

AssertionError: ' --- some text before --- \n\nhallo:<c-u>:call UltiSnips#isExpandable()<cr>:let [truncated]... != ' --- some text before --- \n\n1\n\n --- some text after --- '

   --- some text before --- 

  

- hallo:<c-u>:call UltiSnips#isExpandable()<cr>:let :UltiSnips#isExpandable<cr>cc:0put a

+ 1
```
Before hacking on, I'd like to confirm that it adds something substantial over `UltiSnips#SnippetsInCurrentScope()` already included in UltiSnips.

**Comment by polyzen** [comment]
I'd like to use [this](https://github.com/maralla/completor.vim#use-tab-to-select-completion) for completions in general:
`inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"`

Is there a way to use `isExpandable()` so `<tab>` works for thumbing through completions when they're not snippets?

**Comment by Konfekt** [comment]
You perhaps want 
```vim
let g:ulti_expand_res = 0
function! g:UltiSnips_Expandable()
  call UltiSnips#ExpandSnippet()
  return g:ulti_expand_res
endfunction

 inoremap <expr> <Tab> (g:UltiSnips_Expandable() > 0) ? "" : (pumvisible() ? "\<C-n>") : "\<Tab>")
```

**Comment by polyzen** [comment]
@Konfekt, does the job for regular completions, but throws a ton of errors when it tries to expand a snippet.

**Comment by polyzen** [comment]
Failed to actually use the branch..

Doesn't change the previous behavior. Enters a tab character instead of going to the next completion.

**Comment by Konfekt** [comment]
@polyzen Yes, there was a superfluous `)` , thanks. This mapping does not use any code of this particular branch
```vim
 inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : (g:UltiSnips_Expandable() > 0 ? "" : "\<Tab>")
```
and should work. Does it?

**Comment by polyzen** [comment]
> This mapping does not use any code of this particular branch

Had not noticed that.. Thanks for giving a hand despite that! Wonder what was the cause of the errors.

> should work. Does it?

Same status as before.

**Comment by Konfekt** [comment]
I think you want a mapping that suggests completions if there is no snippet to expand, right? Is it simply
```vim
inoremap <expr> <Tab> (g:UltiSnips_Expandable() > 0) ? "" : "\<C-n>"
```
then?

**Comment by polyzen** [comment]
Same behavior. Will try to think of more options; thanks again!

**Comment by SirVer** [comment]
Rebased and looking at it now. I agree that there is no new functionality in this that `UltiSnips#SnippetsInCurrentScope` does not offer already. @Konfekt don't you agree?

**Comment by Konfekt** [comment]
Yeah, indeed
```vim
function UltiSnips#IsExpandable()
return !empty(UltiSnips#SnippetsInCurrentScope) 
endfunction
```
Because it would have never ocurred to me, to look for this common functionality under the name `UltiSnips#SnippetsInCurrentScope`, it might be helpful to add it anyway. (In particular for those who switch from neosnippet and look for an analog of neosnippet#expandable_or_jumpable and alike).

**Comment by SirVer** [comment]
@Konfekt I hesitate to add functionality just for the sake of discoverability. I'd prefer some way of documenting that the functionality is available in a more general API. I hence prefer to close this PR, I hope for your understanding. 

If you have a suggestion for where to add fitting documentation, please let me know.

**Comment by Konfekt** [comment]
Perhaps in a FAQ entry for neosnippet converts that says that one can mimic `neosnippet#expandable` by
```vim
function UltiSnips#IsExpandable()
  return !empty(UltiSnips#SnippetsInCurrentScope()) 
endfunction
```

**Comment by SirVer** [comment]
@Konfekt wanna craft a PR for that? Since you did not find the information you wanted in the documentation, you are best suited for adding it in a spot where you'd have looked for it.

**Comment by Konfekt** [comment]
Ok.

**Pull request closed without merging**
