### PR TITLE
Fix precompile

### LINKED ISSUE #1428: Error while using vim-snippets
**Expected behavior:**
ifm snippets complete the quotes

**Actual behavior:**
```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new
Please read and follow:
https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/test/.vim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 47, in wrapper
    return func(self, *args, **kwds)
  File "/home/test/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 173, in expand
    if not self._try_expand():
  File "/home/test/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 810, in _try_expand
    self._do_snippet(snippet, before)
  File "/home/test/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 759, in _do_snippet
    snippet_instance = snippet.launch(
  File "/home/test/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/definition/base.py", line 523, in launch
    snippet_instance.update_textobjects(vim_helper.buf)
  File "/home/test/.vim/plugged/ultisnips/pythonx/UltiSnips/text_objects/snippet_instance.py", line 102, in update_textobjects
    if obj._update(done, buf):
  File "/home/test/.vim/plugged/ultisnips/pythonx/UltiSnips/text_objects/python_code.py", line 284, in _update
    exec(compiled_code, self._locals)  # pylint:disable=exec-used
  File "<exec-interpolation-code>", line 1, in <module>
NameError: name 'get_quoting_style' is not defined

Executed snippet code:
  1 > snip.rv = get_quoting_style(snip)
```

### PR DESCRIPTION
**Pull request by ces42**
This fixes #1428 and re-implements #1421. I went for the second approach described in https://github.com/SirVer/ultisnips/pull/1421#issuecomment-1027453551. I also added a test to check that global snippets can be used by snippets that are above them in the file. 

This also fixes the bug I mentioned in https://github.com/SirVer/ultisnips/pull/1421#issuecomment-1031259149 (the bug can be observed by running the new test on 3d78b73265b03b9abe25f223b3e7c9e083d79293)

### CODE REVIEW

**Comment by SirVer** [comment]
@ces42 Code looks good to me, however thee are conflicts against the base branch, hence I cannot run CI for it. Could you fix this?

**Comment by ces42** [comment]
I think I just messed everything up trying to rebase. I'll hopefully figure out how to do this sometime this (or maybe next) weekend.

**Comment by SirVer** [comment]
@ces42 I'd really love to have this change. Can you give it one more shot?

**Comment by ces42** [comment]
Moved to #1470 because I don't know how to fix this git mess...

**Pull request closed without merging**
