### PR TITLE
Docs: alternative implementation of IsExpandable function

### PR DESCRIPTION
**Pull request by unclechu**
To deal with space characters.

### CODE REVIEW

**Comment by unclechu** [comment]
@SirVer Does it look okay?

**Comment by SirVer** [comment]
@unclechu Yes, the doc update looks great to me. I am just wondering if we can test this somehow and make sure it does not regress. But I have no good idea how to test something in the documentation.... Do you have an idea?

**Comment by andreyorst** [comment]
Well we can just feed keys to vim, like <kbd>:</kbd><kbd>h</kbd><kbd>ultisnips</kbd><kbd>/</kbd><kbd>function UltiSnips#IsExpandable()</kbd><kbd>V</kbd><kbd>/</kbd><kbd>endfunction</kbd><kbd>y</kbd><kbd>Ctrl</kbd><kbd>w</kbd><kbd>k</kbd><kbd>P</kbd> and we will have a buffer with copied function contents. But that's silly

**Comment by SirVer** [comment]
I did not come up with a better idea for testing this, so let's get it in as is. Thanks for the contributions @unclechu !

@UltiBot merge

**Pull request merged**
