### PR TITLE
expose text in line before snippet to context conditions (faster on neovim)

### PR DESCRIPTION
**Pull request by ces42**
This would add a `before` attribute to the `snip` object in context conditions. `snip.before` should be equivalent to `snip.buffer[snip.line][:snip.column+1]`. **EDIT:** Actually, it's not because `vim.current.window.cursor` and by extension `snip.column` count bytes, not characters, see https://github.com/neovim/pynvim/issues/383.

However this implementation is faster on neovim (by ~ 0.7 ms) because it avoids an api call and the associated IPC overhead. An additional advantage is that it is more concise and avoids confusion about 1- and 0-based indexing.

If you decide you want to merge this I can write documentation for it.

### CODE REVIEW

**Comment by SirVer** [comment]
So I hate the argument that this is good because it is faster on Neovim.... Working around the design flaws of NeoVim is not really the job of plugins I think. 

I like the convenience argument much better. Let's have it for this reason! Could you add a test + documentation?

**Comment by SirVer** [comment]
@ces42, friendly ping on this.

**Comment by ces42** [comment]
Added doc and test. Sorry this took so long.

Also I found an even better reason to add this: `vim.current.window.cursor` and by extension `snip.column` count bytes, not characters, see https://github.com/neovim/pynvim/issues/383. so using `snip.buffer[snip.line][:snip.column+1]` can lead to all sorts of fun bugs for people using non-ascii characters.

**Comment by SirVer** [comment]
@ces42 Thanks so much!

**Pull request merged**
