### PR TITLE
Add support for deoplete

### PR DESCRIPTION
**Pull request by HerringtonDarkholme**
Deoplete is now stable. https://github.com/SirVer/ultisnips/issues/517

[Review on Reviewable](https://reviewable.io/reviews/sirver/ultisnips/611)

### CODE REVIEW

**Comment by SirVer** [comment]
looks good - might have also used the python API, but for now that seems to be a reasonable implementation. Thanks.

**Comment by s0undt3ch** [comment]
I'm using neovim and have deoplete and ultisnips installed. Deoplete is configured to start at startup and the only ultisnips setting that I've set is:
```vim
  let g:UltiSnipsSnippetsDir        = '~/.nvim/UltiSnips/'
```

I've created a python snippet:
```
snippet log "Instantiate logging" !b
log = logging.getLogger(__name__)
endsnippet
```

Now, I even closed and reopened nvim and, although if I type `#!<tab>` on the top of a python file I get the shebang snippet, I'm unable to do `log<tab>` to get my own snippet to expand and the `log` snippet does not even show on deoplete's completions menu.

What might be doing wrong?

**Comment by s0undt3ch** [comment]
If I add that same log snippet into vim-snippets ultisnips python.snippet file, it works although it still does not show in deoplete's completion menu.

**Comment by seletskiy** [comment]
@HerringtonDarkholme: you're probably interested in @s0undt3ch's issue.

**Comment by HerringtonDarkholme** [comment]
Hi @s0undt3ch, I tried locally, but cannot reproduce your problem. Could you give a minimal setup and test file? I  added you snippet into vim-snippets ultisnips python.snippet file, and the snippet jumps out in a new py file.

screen shot 2016-01-11 at 15 00 51

**Comment by HerringtonDarkholme** [comment]
I guess there has already been a `log` variable in your buffer, and UltiSnip's priority is quite low, so the buffer variable overwrites your snippet.

**Comment by s0undt3ch** [comment]
Yes, there was already a log variable in my buffer.

I'll try to report back with a clean buffer, but it seems that on vim-snippets python.vim works on my setup, my .NVim/Ultisnips/python.vim seems to be ignored...

**Comment by seletskiy** [comment]
@HerringtonDarkholme: Thanks for the assistance!

**Pull request merged**
