### PR TITLE
add g:UltisnipsSnippetStorageDirectoryForUltiSnipsEdit

### PR DESCRIPTION
**Pull request by zhoosch**
Hi SirVer,

I refer to #1287 and hope this will fulfil your expectations.

Greetings
Jan

### CODE REVIEW

**Comment by SirVer** [comment]
@zhoosch Thanks for the PR. I hope I find some time to review it and see why all the tests are failing in CI this week.

**Comment by SirVer** [comment]
@zhoosch I changed some stuff in the implementation and augmented the docs a bit. I also fixed a crash on startup when the new variable was not defined - this also should have fixed the tests. I believe I have kept your functionality in tact, but could you give this a quick whirl and see if it is still behaving as expected?

Thanks for your contribution. From my site this is good to go, I'll wait for your opinion before merging.

**Comment by SirVer** [comment]
@zhoosch Since i will have little time in the coming days I took the liberty of merging as is. I can roll back if you prefer.

**Comment by zhoosch** [comment]
Hi @SirVer,

sorry for being a little bit late. I've tested your changes in this PR.
As you wrote in the documentation i have to provide the `g:UltiSnipsSnippetStorageDirectoryForUltiSnipsEdit` explicit for the snippet engine now.
The first implementation here was more convenient but i think not as predictable in behavior as with your changes.
I've read what you have changed. Thank you for adding this feature! It is a very good and needed improvement for me and hopefully for others too.

Works now in this configuration as expected.
``` viml
    let g:UltiSnipsSnippetStorageDirectoryForUltiSnipsEdit = '/my/own/snippet/storage'
    let g:UltiSnipsSnippetDirectories=[g:UltiSnipsSnippetStorageDirectoryForUltiSnipsEdit, 'UltiSnips']
```

**Pull request merged**
